
project_id = "tpthvlivzxrtkexxzqli"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[functions]
[functions.stripe-webhook]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = true

[functions.create-customer-portal]
verify_jwt = true

[functions.sync-subscription]
verify_jwt = true
