// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tpthvlivzxrtkexxzqli.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwdGh2bGl2enhydGtleHh6cWxpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc4Njk2NTQsImV4cCI6MjA1MzQ0NTY1NH0.p8pQ6mVS8vTLK-SKLjVMx7ccqNTFSfuvrybBUBEzpcA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);